In [1]:
import pandas as pd

In [2]:
import h5py

In [3]:
filename = 'SVHN_single_grey1.h5'
h5f = h5py.File(filename, 'r')
print("Keys: %s" % h5f.keys())


Keys: <KeysViewHDF5 ['X_test', 'X_train', 'X_val', 'y_test', 'y_train', 'y_val']>


In [4]:
#Load the training and test set|

X_train = h5f['X_train'][:]
y_train = h5f['y_train'][:]
X_test = h5f['X_test'][:]
y_test = h5f['y_test'][:]
X_val=h5f['X_val'][:]
y_val=h5f['y_val'][:]

In [5]:
# Reshaping the dataset
X_train = X_train.reshape(X_train.shape[0],1024)
X_test = X_test.reshape(X_test.shape[0],1024)
X_val = X_val.reshape(X_val.shape[0],1024)

In [6]:
# normalising inputs from 0-255 to 0-1
X_train = X_train/255.0
X_test = X_test/255.0
X_val = X_val/255.0

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import datasets
from skimage import exposure
import numpy as np
#import imutils
# import cv2
import matplotlib.pyplot as plt
# calculate accuracy measures and confusion matrix
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

In [8]:
# show the sizes of each data split

print("training data points: {}".format(len(y_train)))
print("validation data points: {}".format(len(y_val)))
print("testing data points: {}".format(len(y_test)))

training data points: 42000
validation data points: 60000
testing data points: 18000


In [9]:
# choosing different k value
k=5
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  5
Classification report
              precision    recall  f1-score   support

           0       0.38      0.66      0.48      1814
           1       0.44      0.70      0.54      1828
           2       0.55      0.52      0.53      1803
           3       0.42      0.39      0.41      1719
           4       0.67      0.61      0.64      1812
           5       0.48      0.36      0.41      1768
           6       0.47      0.38      0.42      1832
           7       0.72      0.58      0.64      1808
           8       0.42      0.33      0.37      1812
           9       0.52      0.36      0.43      1804

   micro avg       0.49      0.49      0.49     18000
   macro avg       0.51      0.49      0.49     18000
weighted avg       0.51      0.49      0.49     18000

Confusion matrix
[[1201   60   44   37   45   45  129   31  109  113]
 [ 125 1285   83   81   84   36   36   58   18   22]
 [ 126  252  932  115   44   44   28  128   69   65]
 [ 164  255  166  677   54 

In [10]:
# choosing different k value
k=10
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  10
Classification report
              precision    recall  f1-score   support

           0       0.43      0.68      0.53      1814
           1       0.46      0.74      0.56      1828
           2       0.58      0.55      0.57      1803
           3       0.42      0.42      0.42      1719
           4       0.65      0.64      0.64      1812
           5       0.49      0.38      0.43      1768
           6       0.49      0.41      0.45      1832
           7       0.73      0.60      0.66      1808
           8       0.46      0.35      0.40      1812
           9       0.56      0.40      0.46      1804

   micro avg       0.52      0.52      0.52     18000
   macro avg       0.53      0.52      0.51     18000
weighted avg       0.53      0.52      0.51     18000

Confusion matrix
[[1240   62   47   38   47   46  111   26   91  106]
 [  94 1344   64   85   79   39   31   41   21   30]
 [ 110  236  991  113   45   31   30  133   46   68]
 [ 134  265  145  719   46

In [11]:
# choosing different k value
k=15
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  15
Classification report
              precision    recall  f1-score   support

           0       0.43      0.68      0.53      1814
           1       0.46      0.73      0.57      1828
           2       0.61      0.55      0.58      1803
           3       0.44      0.43      0.43      1719
           4       0.66      0.65      0.66      1812
           5       0.50      0.39      0.44      1768
           6       0.49      0.40      0.44      1832
           7       0.71      0.62      0.66      1808
           8       0.46      0.36      0.41      1812
           9       0.56      0.42      0.48      1804

   micro avg       0.52      0.52      0.52     18000
   macro avg       0.53      0.52      0.52     18000
weighted avg       0.53      0.52      0.52     18000

Confusion matrix
[[1233   68   39   39   51   46  113   37   86  102]
 [  95 1335   70   83   75   34   32   51   21   32]
 [ 100  215  992  107   55   30   37  138   54   75]
 [ 136  251  136  734   50

In [12]:
# choosing different k value
k=20
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  20
Classification report
              precision    recall  f1-score   support

           0       0.44      0.70      0.54      1814
           1       0.46      0.73      0.56      1828
           2       0.62      0.54      0.58      1803
           3       0.45      0.42      0.44      1719
           4       0.64      0.65      0.65      1812
           5       0.52      0.39      0.45      1768
           6       0.51      0.41      0.46      1832
           7       0.71      0.63      0.67      1808
           8       0.48      0.37      0.42      1812
           9       0.56      0.42      0.48      1804

   micro avg       0.53      0.53      0.53     18000
   macro avg       0.54      0.53      0.52     18000
weighted avg       0.54      0.53      0.52     18000

Confusion matrix
[[1263   66   33   35   51   43  111   40   79   93]
 [  97 1334   60   84   76   27   33   49   32   36]
 [  95  238  979  102   50   31   32  150   49   77]
 [ 130  268  138  727   53

In [13]:
# choosing different k value
k=30
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  30
Classification report
              precision    recall  f1-score   support

           0       0.45      0.70      0.55      1814
           1       0.46      0.74      0.57      1828
           2       0.65      0.53      0.58      1803
           3       0.47      0.43      0.45      1719
           4       0.64      0.65      0.64      1812
           5       0.53      0.41      0.46      1768
           6       0.51      0.42      0.46      1832
           7       0.70      0.63      0.66      1808
           8       0.46      0.36      0.40      1812
           9       0.55      0.45      0.49      1804

   micro avg       0.53      0.53      0.53     18000
   macro avg       0.54      0.53      0.53     18000
weighted avg       0.54      0.53      0.53     18000

Confusion matrix
[[1265   61   31   44   52   34   90   41   74  122]
 [  91 1360   46   82   70   37   34   46   31   31]
 [  89  239  964   99   51   41   28  156   47   89]
 [ 108  270  105  744   54

In [14]:
# choosing different k value
k=100
print("n_neighbors: ",k)
NNH = KNeighborsClassifier(n_neighbors= k )
NNH.fit(X_train, y_train)

#Prediction on test set
predicted_labels = NNH.predict(X_test)

# Accuracy on test set
accuracy =  NNH.score(X_test, y_test)
expected=y_test
print("Classification report")
print(metrics.classification_report(expected, predicted_labels))
print("Confusion matrix")
print(metrics.confusion_matrix(expected, predicted_labels))
print("Overall score ",accuracy)
print("--------------------")

n_neighbors:  100
Classification report
              precision    recall  f1-score   support

           0       0.43      0.71      0.54      1814
           1       0.44      0.73      0.55      1828
           2       0.65      0.50      0.57      1803
           3       0.50      0.42      0.46      1719
           4       0.65      0.64      0.65      1812
           5       0.55      0.41      0.47      1768
           6       0.54      0.41      0.46      1832
           7       0.67      0.62      0.64      1808
           8       0.51      0.39      0.45      1812
           9       0.55      0.47      0.50      1804

   micro avg       0.53      0.53      0.53     18000
   macro avg       0.55      0.53      0.53     18000
weighted avg       0.55      0.53      0.53     18000

Confusion matrix
[[1297   85   26   43   48   30   89   40   45  111]
 [ 117 1331   54   63   69   30   37   62   28   37]
 [ 103  251  902   75   61   50   30  171   58  102]
 [ 133  291   92  721   5

# Conclusion

1) We tried to analyse the SVHN_single_grey1 dataset by using our traditional KNN alogritm by using different neighbors(k) values. The findings are listed below:-

    k=5, Overall score  0.49016666666666664
    
    k=10, Overall score  0.5168333333333334
    
    k=15, Overall score  0.5235555555555556
    
    k=20, Overall score  0.5277222222222222
    
    k=30, Overall score  0.5327777777777778
    
    k=100, Overall score  0.5318333333333334
    
